execute pathogen#infect()
syntax on
filetype plugin indent on

" unset syntaxic check while exiting
let g:syntastic_check_on_wq=0

" set omnicompletion
filetype plugin on
set omnifunc=syntaxcomplete#Complete

" set completion for ruby
autocmd FileType ruby,eruby let g:rubycomplete_buffer_loading = 1 
autocmd FileType ruby,eruby let g:rubycomplete_classes_in_global = 1
autocmd FileType ruby,eruby let g:rubycomplete_rails = 1
